Fix/maint-26838 : Notification is not sent when a modification is done  on a watched wiki page
exodev/wiki pull request #252
Opened 2020-08-17 11:14 UTC by ahmadmido

2020-08-28 13:41 UTC, ahamdi requested changes

2020-08-28 13:41 UTC, ahamdi commented on wiki-service/src/main/java/org/exoplatform/wiki/notification/Utils/NotificationsUtils.java
> +  public static final ArgumentLiteral<Set> RECIVERS = new ArgumentLiteral<Set>(Set.class, "watchers");
```suggestion
  public static final ArgumentLiteral<Set> WATCHERS = new ArgumentLiteral<Set>(Set.class, "watchers");
```

2020-08-28 13:41 UTC, ahamdi commented on wiki-service/src/main/java/org/exoplatform/wiki/notification/listener/EditWikiListener.java
> +      LOG.error("Cannot have list of watchers" + e);
```suggestion
      LOG.error("Cannot have list of watchers" + e);
```
```suggestion
      LOG.error("Cannot have list of watchers for wiki page {} ", page.getName(), e);
```

2020-08-28 13:41 UTC, ahamdi commented on wiki-service/src/main/java/org/exoplatform/wiki/notification/listener/EditWikiListener.java
> +    ctx.append(NotificationsUtils.RECIVERS, receivers);
```suggestion
    ctx.append(NotificationsUtils.WATCHERS, receivers);
```

2020-08-28 13:41 UTC, ahamdi commented on wiki-service/src/main/resources/locale/wiki/service/WikiService_en.properties
> +INotification.label.group.wiki=Wiki
```suggestion
UINotification.label.group.wiki=Wiki
```

2020-08-28 13:41 UTC, ahamdi commented on wiki-service/src/main/resources/locale/wiki/service/WikiService_en.properties
> +Notification.wiki.editWikiNotification=The watched wiki page {0} has been edited by {1}
```suggestion
Notification.wiki.editWikiNotification=The page {0} has been edited by {1}, you are receiving this notification because you are watching this page.
```

2020-08-28 13:41 UTC, ahamdi commented on wiki-service/src/main/resources/locale/wiki/service/WikiService_fr.properties
> +
some labels are missing compared to en file, but it is not an issue since this file will be replaced after Crowdin synchronization

2020-08-28 13:41 UTC, ahamdi commented on wiki-webapp/src/main/webapp/WEB-INF/conf/wiki/resource-bundle-configuration.xml
>      </component-plugin>
Nothing changed here, please remove this file from the PR

2020-08-28 13:41 UTC, ahamdi commented on wiki-webui/src/main/java/org/exoplatform/wiki/webui/control/action/SavePageActionComponent.java
> +            try {
Listener service should be fired from services layer (WikiService class) and not from presentation layer.

2020-09-01 11:46 UTC, ahamdi requested changes

2020-09-01 11:46 UTC, ahamdi commented on wiki-service/src/main/java/org/exoplatform/wiki/service/impl/WikiServiceImpl.java
> +    invalidateCache(page);
Those instructions should be executed before sending notifications, to avoid sen ding them when an error occur when updating the page

2020-09-01 11:46 UTC, ahamdi commented on wiki-webapp/src/main/webapp/WEB-INF/conf/wiki/resource-bundle-configuration.xml
>      </component-plugin>
Please consider my comment here

2020-09-01 12:22 UTC, ahmadmido commented on wiki-service/src/main/java/org/exoplatform/wiki/service/impl/WikiServiceImpl.java
> +    invalidateCache(page);
Done!

2020-09-01 12:23 UTC, ahmadmido commented on wiki-webapp/src/main/webapp/WEB-INF/conf/wiki/resource-bundle-configuration.xml
>      </component-plugin>
Done!

2020-09-01 12:29 UTC, ahamdi approved these changes
LGTM

2020-09-01 22:08 UTC, ahamdi requested changes
Could you add Unit tests for the added functionality

2020-09-09 10:00 UTC, ahamdi requested changes

2020-09-09 10:00 UTC, ahamdi commented on wiki-service/src/test/java/org/exoplatform/wiki/builder/WikiTemplateBuilderTest.java
> +                                   .buildDigest(context, writer));
Those retirns always FALSE , you need to test the MakeMessage function instead.

2020-09-09 10:00 UTC, ahamdi commented on wiki-service/src/test/java/org/exoplatform/wiki/plugin/EditWikiNotificationPluginTest.java
> +    assertNotNull(draftPage);
Why do you need to create a draft page ?

2020-09-09 10:00 UTC, ahamdi commented on wiki-service/src/test/java/org/exoplatform/wiki/service/TestWikiService.java
> +    assertEquals("new page updated", page.getTitle());
Please add the check to verify that the listener is fired when a page is updated

2020-09-10 11:17 UTC, ahamdi approved these changes
LGTM

2020-09-10 11:21 UTC, merged