MAINT-25835: Configure newly created Wiki settings and pages permissions
exodev/wiki pull request #263
Opened 2020-10-12 23:22 UTC by azayati

2020-10-13 17:01 UTC, ahamdi requested changes

2020-10-13 18:16 UTC, azayati commented on wiki-service/src/main/java/org/exoplatform/wiki/jpa/dao/WikiDAO.java
> +
done

2020-10-13 18:17 UTC, azayati commented on wiki-service/src/main/java/org/exoplatform/wiki/jpa/JPADataStorage.java
> +      PermissionEntry anyPermissionEntry = new PermissionEntry(IdentityConstants.ANY, "", IDType.USER, new Permission[] {(
Any means that any member of platform/users have access to the wiki of the private site, it is logical no ?

2020-10-13 18:18 UTC, azayati commented on wiki-service/src/main/java/org/exoplatform/wiki/service/WikiService.java
> +  public List<Wiki> getAllWikis() throws WikiException;
It is added in order to be used by the UP, I will remove it then

2020-10-13 18:25 UTC, azayati commented on wiki-service/src/main/java/org/exoplatform/wiki/service/WikiService.java
> +  public List<Wiki> getAllWikis() throws WikiException;
done

2020-10-14 08:53 UTC, ahamdi commented on wiki-service/src/main/java/org/exoplatform/wiki/jpa/JPADataStorage.java
> +      PermissionEntry anyPermissionEntry = new PermissionEntry(IdentityConstants.ANY, "", IDType.USER, new Permission[] {(
I thought Any means anyone even guest users, isn't it the case ?

2020-10-14 09:34 UTC, ahamdi commented on wiki-service/src/main/java/org/exoplatform/wiki/jpa/JPADataStorage.java
> +      PermissionEntry anyPermissionEntry = new PermissionEntry(IdentityConstants.ANY, "", IDType.USER, new Permission[] {(
OK I think we cna proceed with the merge

2020-10-14 09:35 UTC, ahamdi approved these changes
LGTM

2020-10-14 09:35 UTC, merged